# This is a basic workflow to help you get started with Actions

name: DefiChain Dashboard

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Berlin"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas bs4
      - name: Run scraper
        run: |
          python get_prices.py
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "jesjehle@gmx.de"
          git config --local user.name "JesJehle"
          git add ./prices.csv
          git commit -m "update"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
